# Generated by Django 2.1.7 on 2019-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('foodreview', '0002_auto_20190227_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
